#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname "$0")/config"

if [[ ! -f /usr/local/bin/acmetool ]]; then
  wget --quiet "$ACME_CLIENT_URL" -O- | tar zx --no-anchor acmetool --strip-components 2 -C /usr/local/bin
  /usr/local/bin/acmetool quickstart --response-file="$(dirname "$0")/response.yaml"
fi

if [[ ! -f /etc/sudoers.d/dokku-acmetool ]]; then
  echo "%dokku ALL=(ALL) NOPASSWD:/usr/local/bin/acmetool *" > /etc/sudoers.d/dokku-acmetool
fi
